version: "3"
services:
  db:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  web:
    tty: true
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ../:/app
    working_dir: /app
    container_name: "web"
    links:
      - "db"
