version: "3"
services:
  db:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    container_name: "insta-sample-db"

  web:
    tty: true
    build:
      context: .
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ../:/app
    working_dir: /app
    container_name: "insta-sample-web"
    links:
      - "db"
 
